version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-quickstart"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bqb8feb8nrx9"
s3_prefix = "aws-sam-quickstart"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
